[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/C/rpc"
linea_goerli = "https://rpc.goerli.linea.build"

[etherscan]
fuji  = { key = "${FUJIAPI_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
